import { basename } from "./normalize.js";

const $ = id => document.getElementById(id);
let report,autoStopTimer;
const background=chrome.runtime.connect({name:"weblens-panel"}), pending=new Map();let nextMessageId=1;
const send=message=>new Promise((resolve,reject)=>{const id=nextMessageId++;pending.set(id,{resolve,reject});background.postMessage({...message,id});});
background.onMessage.addListener(message=>{
  if(message.type==="PROGRESS"&&message.tabId===chrome.devtools.inspectedWindow.tabId){showProgress(message.percent,message.label);return;}
  if(message.type!=="RESPONSE")return;const request=pending.get(message.id);if(!request)return;pending.delete(message.id);
  if(message.ok)request.resolve(message.data);else request.reject(new Error(message.error||"Unknown extension error"));
});
background.onDisconnect.addListener(()=>{const error=new Error(chrome.runtime.lastError?.message||"The WebDive background worker stopped unexpectedly. Reload the extension and try again.");for(const request of pending.values())request.reject(error);pending.clear();});
setInterval(()=>{try{background.postMessage({type:"KEEPALIVE"});}catch{}},20000);
const bytes = value => value < 1024 ? `${value} B` : value < 1048576 ? `${(value / 1024).toFixed(1)} KB` : `${(value / 1048576).toFixed(1)} MB`;
const debounce=(fn,delay=220)=>{let timer;return(...args)=>{clearTimeout(timer);timer=setTimeout(()=>fn(...args),delay);};};
const pct = (used, total) => total ? `${Math.round((total - used) / total * 100)}% unused` : "n/a";
const rows = (items, value) => items.length ? items.map(item => `<tr><td title="${escape(item.url)}">${escape(basename(item.url))}</td><td>${value(item)}</td></tr>`).join("") : `<tr><td colspan="2">None</td></tr>`;
const escape = value => String(value).replace(/[&<>"']/g, c => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" }[c]));
const help=(label,description)=>`<span class="help" tabindex="0" data-tip="${escape(description)}">${escape(label)}<span aria-hidden="true">?</span></span>`;
const showProgress=(percent,label)=>{$("notice").innerHTML=`<div class="progress-copy"><span>${escape(label)}</span><b>${percent}%</b></div><div class="progress-track" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${percent}" aria-label="${escape(label)}"><i style="width:${percent}%"></i></div>`;};

const findingReport=(finding,file)=>{const reports={
  "CPU-heavy":{evidence:`${file.cpuMs.toFixed(1)} ms across ${file.cpuSamples} samples (${file.cpuPercent.toFixed(1)}% of URL-attributed CPU).`,impact:"This script consumed a large share of sampled JavaScript CPU and can delay interaction and rendering.",action:"Inspect hot functions in Performance, reduce repeated work, split expensive computation, or move suitable work to a worker."},
  "blocks main thread":{evidence:`${file.blockingMs.toFixed(1)} ms blocking estimate across ${file.longTasks} long tasks.`,impact:"Work beyond the first 50 ms of a task can delay input processing and worsen responsiveness.",action:"Break synchronous work into smaller tasks and inspect this script’s callbacks. This attribution is a correlation: shared blocking time is divided among contributing URLs."},
  "mostly unused":{evidence:`${bytes(file.unusedBytes||0)} of ${bytes(file.totalBytes||0)} (${file.unusedPercent||0}%) was not exercised during this journey.`,impact:"Unused code still costs transfer, decompression, parsing, compilation, and memory.",action:"Use route-level splitting, defer optional features, remove dead dependencies, and validate other important journeys before deleting code."},
  "high V8 compile/parse":{evidence:`${file.v8Ms.toFixed(1)} ms across ${file.v8Events} attributed V8 parse/compile events.`,impact:"Compilation work occupies the main thread before code can execute.",action:"Ship less JavaScript, split large bundles, avoid repeated dynamic compilation, and defer non-critical modules."}
};const item=reports[finding];return item?`<article class="finding-card"><h3>${escape(finding)}</h3><p><strong>Evidence:</strong> ${escape(item.evidence)}</p><p><strong>Impact:</strong> ${escape(item.impact)}</p><p><strong>Next action:</strong> ${escape(item.action)}</p></article>`:"";};
function renderHighlightedSource(pre,source,ranges){const fragment=document.createDocumentFragment();let cursor=0;for(const range of ranges){const start=Math.max(cursor,Math.min(source.length,range.startOffset)),end=Math.max(start,Math.min(source.length,range.endOffset));if(start>cursor){const span=document.createElement("span");span.className="source-unused";span.textContent=source.slice(cursor,start);fragment.append(span);}if(end>start){const span=document.createElement("span");span.className="source-used";span.textContent=source.slice(start,end);fragment.append(span);}cursor=Math.max(cursor,end);}if(cursor<source.length){const span=document.createElement("span");span.className="source-unused";span.textContent=source.slice(cursor);fragment.append(span);}pre.replaceChildren(fragment);}
async function openFileDetail(file){const dialog=$("file-detail");$("detail-title").textContent=basename(file.url);$("detail-url").textContent=file.url;$("detail-body").innerHTML='<div class="empty-detail">Loading locally stored analysis…</div>';dialog.showModal();
  const metrics=`<div class="detail-metrics"><div class="metric"><span>Priority</span><b class="priority-${String(file.priority).toLowerCase()}">${escape(file.priority)} · ${file.priorityScore}</b></div><div class="metric"><span>Observed</span><b>${escape(file.loadContext||'Requested during recording')}</b></div><div class="metric"><span>Transfer</span><b>${bytes(file.transferBytes)}</b></div><div class="metric"><span>Source</span><b>${file.totalBytes==null?'—':bytes(file.totalBytes)}</b></div><div class="metric"><span>Unused</span><b>${file.unusedBytes==null?'n/a':`${bytes(file.unusedBytes)} · ${file.unusedPercent}%`}</b></div><div class="metric"><span>CPU</span><b>${file.cpuMs.toFixed(1)} ms</b></div><div class="metric"><span>Blocking</span><b>${file.blockingMs.toFixed(1)} ms</b></div><div class="metric"><span>Long tasks</span><b>${file.longTasks}</b></div></div><article class="finding-card"><h3>Why this priority?</h3><p>${escape(file.priorityReason)}. Score = blocking × 4 + CPU + V8 compile/parse × 2 + unused JS KiB ÷ 2.</p></article>`;
  const findings=file.findings.length?`<h2>Finding reports</h2><div class="finding-report">${file.findings.map(finding=>findingReport(finding,file)).join("")}</div>`:'<div class="finding-card"><h3>No threshold finding</h3><p>This resource did not cross the current finding thresholds. Its measured values are still shown above.</p></div>';
  let detail=null;try{if(file.detailAvailable)detail=await send({type:"GET_FILE_DETAIL",recordingId:report.recording.startedAt,url:file.url});}catch(error){$("detail-body").innerHTML=metrics+findings+`<div class="empty-detail">Could not load source detail: ${escape(error.message)}</div>`;return;}
  if(!detail){$("detail-body").innerHTML=metrics+findings+'<div class="empty-detail">Used/unused source coverage is not applicable or was unavailable for this resource.</div>';return;}
  const modules=detail.originalModules||[],sourceMapSection=detail.kind==="JavaScript"?(modules.length?`<div class="source-map-section"><div class="source-toolbar"><h2>Original modules from source map (${modules.length})</h2><span class="muted">${escape(detail.sourceMapUrl||"")}</span></div><div class="module-table"><table><thead><tr><th>Original source</th><th class="num">Mapped bytes</th><th class="num">Used</th><th class="num">Unused</th><th class="num">Unused %</th></tr></thead><tbody>${modules.map(module=>`<tr><td title="${escape(module.source)}">${escape(module.source)}</td><td class="num">${bytes(module.generatedBytes)}</td><td class="num">${bytes(module.usedGeneratedBytes)}</td><td class="num unused">${bytes(module.unusedGeneratedBytes)}</td><td class="num">${module.unusedPercent}%</td></tr>`).join("")}</tbody></table></div></div>`:`<article class="finding-card source-map-note"><h3>Source-map attribution unavailable</h3><p>Status: ${escape(detail.sourceMapStatus||"not declared")}${detail.sourceMapUrl?` · ${escape(detail.sourceMapUrl)}`:""}.</p><p>The generated bundle coverage below remains exact; original-module attribution requires an accessible source map.</p></article>`):"";
  $("detail-body").innerHTML=metrics+findings+sourceMapSection+`<div class="source-toolbar"><h2>${escape(detail.kind)} coverage source</h2><div class="coverage-legend"><span><i class="used-key"></i>Used</span><span><i class="unused-key"></i>Unused in this journey</span></div></div><pre id="coverage-source" class="source-view"></pre>`;
  await new Promise(resolve=>requestAnimationFrame(resolve));renderHighlightedSource($("coverage-source"),detail.source,detail.usedRanges||[]);
}

function render(data) {
  const s = data.summary;
  const t = data.traceAnalysis;
  const ms = value => value < 1000 ? `${value.toFixed(1)} ms` : `${(value/1000).toFixed(2)} s`;
  const journey=data.journey||{phases:[],interactions:[]};
  const phaseRows=journey.phases.map(phase=>`<tr><td>${escape(phase.name)}</td><td class="num">${ms(phase.startMs)}–${ms(phase.endMs)}</td><td class="num">${phase.requestCount}</td><td class="num">${bytes(phase.transferBytes)}</td><td class="num">${ms(phase.mainThreadBusyMs)}</td><td class="num">${ms(phase.jsExecutionMs)}</td><td class="num">${phase.longTasks}</td><td>${phase.topScripts.map(item=>escape(basename(item.url))).join(", ")||"—"}</td></tr>`).join("");
  const interactionRows=journey.interactions.map(interaction=>`<tr><td><span class="interaction-chip">${escape(interaction.type)}</span></td><td class="num">${ms(interaction.atMs)}</td><td class="num">${ms(interaction.durationMs)}</td><td class="num">${interaction.requestCount}</td><td class="num">${ms(interaction.mainThreadBusyMs)}</td><td class="num">${interaction.longTasks}</td><td>${interaction.topScripts.map(item=>escape(basename(item.url))).join(", ")||"—"}</td></tr>`).join("");
  const journeySection=`<div class="section"><div class="section-head"><h2>Journey phases &amp; interactions</h2><span class="muted">Manual phase boundaries plus input events observed in the CDP trace</span></div><details open class="event-breakdown"><summary>Phases (${journey.phases.length})</summary><table class="journey-table"><thead><tr><th>Phase</th><th class="num">Time</th><th class="num">Requests</th><th class="num">Transfer</th><th class="num">Main thread</th><th class="num">JS event time</th><th class="num">Long tasks</th><th>Top scripts</th></tr></thead><tbody>${phaseRows||'<tr><td colspan="8">No phase timing was available.</td></tr>'}</tbody></table></details><details class="event-breakdown"><summary>Automatic interaction markers (${journey.interactions.length})</summary><p class="muted">Each marker summarizes work until the next interaction, capped at one second. Temporal correlation does not prove causation.</p><table class="journey-table"><thead><tr><th>Input</th><th class="num">At</th><th class="num">Dispatch</th><th class="num">Requests</th><th class="num">Main thread</th><th class="num">Long tasks</th><th>Top scripts</th></tr></thead><tbody>${interactionRows||'<tr><td colspan="7">No supported input dispatch events were present in this trace.</td></tr>'}</tbody></table></details></div>`;
  const columns=[
    ["name","File","Resource filename. Click a row for complete findings and used/unused source.","text"],["host","Host","Domain that delivered the resource. Third-party hosts often add network and execution cost.","text"],["type","Type","CDP resource category such as Script, Stylesheet, Image, Font, XHR, or Document.","type"],["loadContext","Observed","Whether the resource generated a request during recording or was already loaded and recovered through coverage.","text"],["priority","Priority","JS improvement priority derived from blocking, CPU, V8 compile/parse, and unused bytes.","text"],["priorityScore","Score","Comparable JS priority score. Higher values indicate a stronger measured optimization opportunity.","number"],["priorityReason","Priority driver","The largest factor contributing to this resource's priority score.","text"],["sourceMapStatus","Source map","Whether Chrome exposed an accessible source map for original-module attribution.","text"],["originalModuleCount","Modules","Original source modules attributed through the bundle's source map.","number"],
    ["transferBytes","Transfer","Encoded bytes transferred over the network, including protocol overhead reported by Chrome.","number"],["downloadMs","Download","Elapsed request time from request start until Chrome reports loading finished.","number"],["totalBytes","Source","UTF-8 source bytes for JS/CSS, or decoded response bytes for other resources.","number"],
    ["usedBytes","Used","JS/CSS source bytes whose precise coverage range executed or matched during this journey.","number"],["unusedBytes","Unused","JS/CSS source bytes never exercised during the journey. More unused code increases download and parse cost.","number"],["unusedPercent","Unused %","Unused source divided by total source. High values suggest splitting, deferring, or removing code.","number"],
    ["cpuMs","CPU","Self CPU time attributed to this script by V8 sampling.","number"],["cpuPercent","CPU %","Share of all URL-attributed sampled CPU time consumed by this script.","number"],["cpuSamples","Samples","Number of V8 profiler samples whose top frame belonged to this resource.","number"],
    ["jsInvocations","JS calls","FunctionCall and EvaluateScript trace events attributed to this resource.","number"],["jsExecutionMs","JS event time","Duration of attributed FunctionCall and EvaluateScript trace events; nested events can overlap.","number"],["v8Events","V8 events","Attributed V8 parse and compilation events. Frequent compilation can delay interactivity.","number"],
    ["v8Ms","V8 time","Time spent in attributed V8 parse and compilation events.","number"],["blockingMs","Blocking","Long-task time beyond 50 ms, divided among scripts contributing to each task.","number"],["longTasks","Long tasks","Main-renderer RunTask events over 50 ms to which this resource contributed.","number"],["findings","Findings","Automatic resource-level warnings based on CPU, blocking, coverage, and V8 costs.","text"]
  ];
  const header=columns.map(([key,label,description])=>`<th draggable="true" data-column="${key}" class="${columns.indexOf(columns.find(x=>x[0]===key))>=3&&key!=="findings"?'num ':''}${key==="priorityScore"?'active desc':''}" ${key!=="findings"?`data-sort="${key}"`:''}>${help(label,description)}</th>`).join("");
  const filters=columns.map(([key,,description,kind])=>`<th data-column="${key}">${kind==="type"?`<select data-filter="${key}" aria-label="Filter resource type"><option value="">All</option>${[...new Set(data.files.map(x=>x.type))].sort().map(type=>`<option>${escape(type)}</option>`).join("")}</select>`:`<input data-filter="${key}" type="${kind}" min="0" step="any" placeholder="${kind==="number"?'Min':'Filter'}" aria-label="Filter ${escape(key)}" title="${escape(description)}">`}</th>`).join("");
  $("report").innerHTML = `<h2>Recording: ${escape(data.recording.name)}</h2><div class="grid">
    <div class="card blue">${help("Resources","Network requests observed during recording plus pre-existing JS/CSS recovered from coverage. Transfer counts only recording-time requests.")}<b>${s.totalResources}</b>${s.networkResources??s.totalResources} requested · ${s.preExistingResources||0} pre-existing · ${bytes(s.transferBytes)} transferred</div>
    <div class="card violet">${help("JavaScript","External JavaScript resources observed by Network plus precise execution coverage from V8.")}<b>${s.jsResources}</b>${bytes(s.jsTransferBytes)} downloaded · ${pct(s.jsUsedBytes,s.jsTotalBytes)}</div>
    <div class="card amber">${help("Unused JS","JavaScript source bytes that were downloaded but never executed during this specific journey.")}<b>${bytes(s.jsUnusedBytes)}</b>${s.completelyUnusedJs} completely unused</div>
    <div class="card cyan">${help("CSS","Stylesheets tracked through CSS rule-usage coverage. Unused means no matching rule during the journey.")}<b>${s.cssResources}</b>${bytes(s.cssUnusedBytes)} unused · ${pct(s.cssUsedBytes,s.cssTotalBytes)}</div>
    <div class="card red">${help("Long tasks","Main-thread tasks longer than 50 ms. They can delay input handling, rendering, and responsiveness.")}<b>${s.longTasks}</b>${s.scriptsContributing} scripts contributing</div></div>
    <div class="section"><div class="section-head"><h2>Trace analysis</h2></div><div class="grid trace-grid">
      <div class="card">${help("Main thread busy","Total RunTask time on the renderer main thread. High utilization leaves less time for input and rendering.")}<b>${t.mainThreadBusyPercent.toFixed(0)}%</b>${ms(t.mainThreadBusyMs)} of ${ms(t.durationMs)}</div>
      <div class="card">${help("Heavy interaction tasks","RunTask events containing a FunctionCall or style update over 50 ms; this is a heuristic and does not prove scrolling caused the work.")}<b>${t.scroll.count}</b>P50 ${ms(t.scroll.p50Ms)} · P90 ${ms(t.scroll.p90Ms)} · ${escape(t.scroll.bottleneck)} bottleneck</div>
      <div class="card">${help("Forced reflows","Repeated JavaScript-to-layout alternation within one task. It causes synchronous layout work and visual jank.")}<b>${t.forcedReflow.count}</b>${ms(t.forcedReflow.layoutMs)} forced layout</div>
      <div class="card">${help("Style recalculation","UpdateLayoutTree operations and affected element counts. Large values can make DOM/class changes expensive.")}<b>${t.styleRecalc.count}</b>${t.styleRecalc.averageElements.toFixed(0)} avg · ${t.styleRecalc.maxElements} max elements</div>
      <div class="card">${help("Dirty layout objects","Objects requiring layout recalculation. A high dirty ratio means layout changes affect a broad part of the page.")}<b>${t.layoutDirty.maxDirty}</b>${t.layoutDirty.averageDirty.toFixed(0)} avg · ${t.layoutDirty.averageRatio.toFixed(1)}% dirty</div>
      <div class="card">${help("Garbage collection","V8 memory-reclamation time. Major collections are typically more disruptive than minor collections.")}<b>${ms(t.gc.majorMs+t.gc.minorMs)}</b>${ms(t.gc.majorMs)} major · ${ms(t.gc.minorMs)} minor</div></div>
      <details class="event-breakdown"><summary>Event breakdown (${t.eventStats.length})</summary><table><thead><tr><th>Event</th><th class="num">Count</th><th class="num">Total</th><th class="num">Average</th><th class="num">Trace %</th></tr></thead><tbody>${t.eventStats.map(x=>`<tr><td>${escape(x.name)}</td><td class="num">${x.count}</td><td class="num">${ms(x.totalMs)}</td><td class="num">${ms(x.averageMs)}</td><td class="num">${x.tracePercent.toFixed(1)}%</td></tr>`).join("")||'<tr><td colspan="5">No matching trace events</td></tr>'}</tbody></table></details></div>
    ${journeySection}<div class="section resource-section"><div class="section-head"><h2>All files loaded <span id="visible-count">${data.files.length}</span> / ${data.files.length}</h2><div class="table-actions"><span class="muted drag-hint">Drag headers to reorder</span><button id="copy-csv" class="secondary">Copy CSV</button><button id="reset-columns" class="secondary">Reset columns</button><button id="clear-filters" class="secondary">Clear filters</button></div></div>
      <div class="table-wrap"><table id="resource-table"><thead><tr>${header}</tr><tr class="filter-row">${filters}</tr></thead><tbody id="file-rows"></tbody></table></div></div>`;
  const defaultOrder=columns.map(column=>column[0]);let columnOrder=JSON.parse(localStorage.getItem("weblens-column-order")||"null");
  if(!Array.isArray(columnOrder)||columnOrder.length!==defaultOrder.length||columnOrder.some(key=>!defaultOrder.includes(key)))columnOrder=[...defaultOrder];
  let sort={key:"priorityScore",direction:-1}, activeFilters={}, visibleFiles=[];
  const applyColumnOrder=()=>document.querySelectorAll("#resource-table tr").forEach(row=>{const cells=[...row.children];cells.forEach((cell,index)=>{if(!cell.dataset.column)cell.dataset.column=defaultOrder[index];});const byKey=new Map(cells.map(cell=>[cell.dataset.column,cell]));columnOrder.forEach(key=>{if(byKey.get(key))row.append(byKey.get(key));});});
  const renderFiles = () => {
    const files=data.files.map(file=>({...file,name:basename(file.url)})).filter(file=>Object.entries(activeFilters).every(([key,value])=>{if(value==="")return true;const source=key==="findings"?file.findings.join(" "):file[key];return typeof source==="number"?source>=Number(value):String(source??"").toLowerCase().includes(value.toLowerCase());}));
    files.sort((a,b)=>{const av=a[sort.key],bv=b[sort.key];if(av==null&&bv==null)return 0;if(av==null)return 1;if(bv==null)return -1;return (typeof av==="string"?av.localeCompare(bv):av-bv)*sort.direction;});
    visibleFiles=files;
    const timing=value=>value?value<1000?`${value.toFixed(1)} ms`:`${(value/1000).toFixed(2)} s`:'—';
    $("file-rows").innerHTML=files.map((file,index)=>`<tr data-file-index="${index}" title="Open complete resource analysis"><td class="url" title="${escape(file.url)}">${escape(file.name)}</td><td class="host" title="${escape(file.host)}">${escape(file.host||'—')}</td><td>${escape(file.type)}</td><td>${escape(file.loadContext||'Requested during recording')}</td><td class="priority-${String(file.priority).toLowerCase()}">${escape(file.priority)}</td><td class="num">${file.priorityScore}</td><td>${escape(file.priorityReason)}</td><td>${escape(file.sourceMapStatus||'not applicable')}</td><td class="num">${file.originalModuleCount||'—'}</td><td class="num">${bytes(file.transferBytes)}</td><td class="num">${file.downloadMs==null?'—':timing(file.downloadMs)}</td><td class="num">${file.totalBytes==null?'<span class="muted">—</span>':bytes(file.totalBytes)}</td><td class="num">${file.usedBytes==null?'<span class="muted">n/a</span>':bytes(file.usedBytes)}</td><td class="num ${file.unusedBytes>0?'unused':''}">${file.unusedBytes==null?'<span class="muted">n/a</span>':bytes(file.unusedBytes)}</td><td class="num ${file.unusedPercent===100?'zero':''}">${file.unusedPercent==null?'<span class="muted">n/a</span>':`${file.unusedPercent}%`}</td><td class="num">${timing(file.cpuMs)}</td><td class="num">${file.cpuPercent?`${file.cpuPercent.toFixed(1)}%`:'—'}</td><td class="num">${file.cpuSamples||'—'}</td><td class="num">${file.jsInvocations||'—'}</td><td class="num">${timing(file.jsExecutionMs)}</td><td class="num">${file.v8Events||'—'}</td><td class="num">${timing(file.v8Ms)}</td><td class="num ${file.blockingMs?'zero':''}">${timing(file.blockingMs)}</td><td class="num">${file.longTasks||'—'}</td><td class="findings">${file.findings.length?file.findings.map(x=>`<span>${escape(x)}</span>`).join(''):'<span class="muted">—</span>'}</td></tr>`).join("");
    $("visible-count").textContent=files.length;
    applyColumnOrder();
    $("file-rows").querySelectorAll("tr").forEach(row=>row.addEventListener("click",()=>openFileDetail(visibleFiles[Number(row.dataset.fileIndex)])));
  };
  renderFiles();
  document.querySelectorAll("[data-filter]").forEach(input=>{const apply=()=>{activeFilters[input.dataset.filter]=input.value;renderFiles();};input.addEventListener(input.tagName==="SELECT"?"change":"input",input.tagName==="SELECT"?apply:debounce(apply));});
  $("clear-filters").addEventListener("click",()=>{activeFilters={};document.querySelectorAll("[data-filter]").forEach(input=>input.value="");renderFiles();});
  $("copy-csv").addEventListener("click",async()=>{
    const csvValue=value=>`"${String(value??"").replaceAll('"','""')}"`;
    const orderedColumns=columnOrder.map(key=>columns.find(column=>column[0]===key));
    const lines=[orderedColumns.map(column=>csvValue(column[1])).join(","),...visibleFiles.map(file=>orderedColumns.map(([key])=>csvValue(key==="findings"?file.findings.join("; "):file[key])).join(","))];
    const button=$("copy-csv");
    const csv=lines.join("\r\n");
    try{await navigator.clipboard.writeText(csv);button.textContent=`Copied ${visibleFiles.length} rows`;}
    catch(error){const textarea=document.createElement("textarea");textarea.value=csv;document.body.append(textarea);textarea.select();const copied=document.execCommand("copy");textarea.remove();button.textContent=copied?`Copied ${visibleFiles.length} rows`:"Copy failed";button.title=copied?"":error.message;}
    setTimeout(()=>{button.textContent="Copy CSV";},1800);
  });
  let draggedColumn;
  document.querySelectorAll("thead tr:first-child th[data-column]").forEach(header=>{
    header.addEventListener("dragstart",event=>{draggedColumn=header.dataset.column;header.classList.add("dragging");event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/plain",draggedColumn);});
    header.addEventListener("dragend",()=>{header.classList.remove("dragging");document.querySelectorAll("th.drop-target").forEach(item=>item.classList.remove("drop-target"));});
    header.addEventListener("dragover",event=>{event.preventDefault();if(header.dataset.column!==draggedColumn)header.classList.add("drop-target");});
    header.addEventListener("dragleave",()=>header.classList.remove("drop-target"));
    header.addEventListener("drop",event=>{event.preventDefault();const target=header.dataset.column;if(!draggedColumn||target===draggedColumn)return;columnOrder.splice(columnOrder.indexOf(draggedColumn),1);columnOrder.splice(columnOrder.indexOf(target),0,draggedColumn);localStorage.setItem("weblens-column-order",JSON.stringify(columnOrder));applyColumnOrder();});
  });
  $("reset-columns").addEventListener("click",()=>{columnOrder=[...defaultOrder];localStorage.removeItem("weblens-column-order");applyColumnOrder();});
  document.querySelectorAll("th[data-sort]").forEach(header=>header.addEventListener("click",()=>{
    const key=header.dataset.sort; sort=sort.key===key?{key,direction:-sort.direction}:{key,direction:key==="name"||key==="host"||key==="type"?1:-1};
    document.querySelectorAll("th[data-sort]").forEach(item=>item.classList.remove("active","asc","desc"));
    header.classList.add("active",sort.direction===1?"asc":"desc"); renderFiles();
  }));
  $("report").hidden = false; $("raw").textContent = JSON.stringify(data, null, 2); $("download").disabled = false;
}

const recordingConditions=()=>({cpuRate:Number($("cpu").value),network:$("network").value,coverage:$("coverage").value});
const setRecordingControls=active=>{$("start").disabled=active;$("stop").disabled=!active;$("cpu").disabled=active;$("network").disabled=active;$("coverage").disabled=active;$("quick-reload").disabled=active;$("quick-reload-clean").disabled=active;$("phase-name").disabled=!active;$("mark-phase").disabled=!active;if(!active)$("phase-count").textContent="Start recording to add phase boundaries.";};
$("start").addEventListener("click", async () => {
  try { await send({ type:"START", tabId: chrome.devtools.inspectedWindow.tabId, name: $("name").value.trim() || "Untitled journey", conditions:recordingConditions() });
    setRecordingControls(true); $("phase-count").textContent="No manual phase boundaries yet."; $("notice").textContent = "Recording… manually reload now to capture the initial page load, then complete the journey and press Stop.";
  } catch (e) { $("notice").textContent = `Could not start: ${e.message}`; }
});
$("mark-phase").addEventListener("click",async()=>{const name=$("phase-name").value.trim();if(!name){$("phase-name").focus();return;}try{const marker=await send({type:"MARK_PHASE",tabId:chrome.devtools.inspectedWindow.tabId,name});$("phase-name").value="";$("phase-count").textContent=`${name} started at ${(marker.atMs/1000).toFixed(1)} s`;$("notice").textContent=`Marked journey phase: ${name}. Recording continues.`;}catch(error){$("notice").textContent=`Could not mark phase: ${error.message}`;}});
$("phase-name").addEventListener("keydown",event=>{if(event.key==="Enter"&&!$("mark-phase").disabled)$("mark-phase").click();});
$("stop").addEventListener("click", async () => {
  clearTimeout(autoStopTimer);
  $("stop").disabled = true; showProgress(2,"Stopping recording");
  try { report=await send({ type:"STOP", tabId: chrome.devtools.inspectedWindow.tabId });showProgress(100,"Report complete");await new Promise(resolve=>setTimeout(resolve,200));render(report);await refreshHistory(report.recording.startedAt); $("notice").textContent = "Complete. Report and source details were saved to local history."; }
  catch (e) { $("notice").textContent = `Could not stop: ${e.message}`; }
  finally { setRecordingControls(false); }
});
async function reloadAndAutoRecord(ignoreCache){try{await send({type:"START",tabId:chrome.devtools.inspectedWindow.tabId,name:$("name").value.trim()||"Page load",conditions:{...recordingConditions(),quickAction:ignoreCache?"reload-no-cache":"reload"}});setRecordingControls(true);$("notice").textContent="Reloading and recording… WebDive will stop after load and 1.5 seconds of network quiet.";await new Promise(resolve=>setTimeout(resolve,250));chrome.devtools.inspectedWindow.reload({ignoreCache});const check=async()=>{try{const status=await send({type:"AUTO_STATUS",tabId:chrome.devtools.inspectedWindow.tabId});if(!status.active)return;if(status.ready){$("notice").textContent=status.reason==="maximum-wait"?"Maximum 60-second wait reached; generating the report.":"Load completed and network is quiet; generating the report.";$("stop").click();return;}$("notice").textContent=`Reload recording… ${status.loadFired?"page loaded; waiting for network quiet":"waiting for page load"} (${(status.elapsedMs/1000).toFixed(1)} s)`;autoStopTimer=setTimeout(check,500);}catch(error){$("notice").textContent=`Auto-stop check failed: ${error.message}. Press Stop to finish manually.`;}};autoStopTimer=setTimeout(check,500);}catch(error){setRecordingControls(false);$("notice").textContent=`Could not start reload recording: ${error.message}`;}}
$("quick-reload").addEventListener("click",()=>reloadAndAutoRecord(false));
$("quick-reload-clean").addEventListener("click",()=>reloadAndAutoRecord(true));
$("clear-report").addEventListener("click",()=>{report=undefined;$("report").hidden=true;$("raw").textContent="";$("download").disabled=true;$("notice").textContent="Current view cleared. Saved run history was not changed.";});
$("download").addEventListener("click", () => {
  const url = URL.createObjectURL(new Blob([JSON.stringify(report,null,2)], {type:"application/json"}));
  const a = document.createElement("a"); a.href=url; a.download=`webdive-${Date.now()}.json`; a.click(); URL.revokeObjectURL(url);
});

if (chrome.devtools.performance) {
  chrome.devtools.performance.onProfilingStarted.addListener(() => {
    $("notice").textContent = "Chrome Performance panel started recording. Its Tracing session may contend with WebDive Tracing.start; Network and Coverage remain separate.";
  });
  chrome.devtools.performance.onProfilingStopped.addListener(() => {
    $("notice").textContent = "Chrome Performance panel stopped recording. WebDive controls and reads only its own CDP session.";
  });
}
$("detail-close").addEventListener("click",()=>$("file-detail").close());
$("file-detail").addEventListener("click",event=>{if(event.target===$("file-detail"))$("file-detail").close();});

async function refreshHistory(selectedId){const items=await send({type:"LIST_RECORDINGS"}),select=$("history");select.innerHTML=items.length?items.map(item=>`<option value="${item.id}">${escape(item.name)} · ${new Date(item.startedAt).toLocaleString()} · ${item.resources} resources</option>`).join(""):'<option value="">No saved recordings yet</option>';if(selectedId&&items.some(item=>String(item.id)===String(selectedId)))select.value=String(selectedId);const enabled=!!select.value;$("history-load").disabled=!enabled;$("history-export").disabled=!enabled;$("history-delete").disabled=!enabled;}
$("history").addEventListener("change",()=>{const enabled=!!$("history").value;$("history-load").disabled=!enabled;$("history-export").disabled=!enabled;$("history-delete").disabled=!enabled;});
$("history-load").addEventListener("click",async()=>{const loaded=await send({type:"LOAD_RECORDING",recordingId:Number($("history").value)});if(!loaded)return;report=loaded;render(report);$("notice").textContent=`Loaded saved recording from ${new Date(report.recording.startedAt).toLocaleString()}.`;});
$("history-delete").addEventListener("click",async()=>{const id=Number($("history").value);if(!id||!confirm("Delete this recording and its locally stored source details?"))return;await send({type:"DELETE_RECORDING",recordingId:id});if(report?.recording?.startedAt===id){report=undefined;$("report").hidden=true;$("raw").textContent="";$("download").disabled=true;}await refreshHistory();});
$("history-export").addEventListener("click",async()=>{const id=Number($("history").value),saved=await send({type:"LOAD_RECORDING",recordingId:id}),files=saved.files.filter(file=>file.detailAvailable),parts=[`{"format":"webdive-backup","version":1,"report":${JSON.stringify(saved)},"details":[`];let first=true,index=0;for(const file of files){const detail=await send({type:"GET_FILE_DETAIL",recordingId:id,url:file.url});if(detail){parts.push(first?"":",",JSON.stringify(detail));first=false;}index++;$("notice").textContent=`Preparing backup ${index} / ${files.length}`;}parts.push("]}");const blob=new Blob(parts,{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`webdive-backup-${id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$("notice").textContent="Backup ready. Keep it outside the browser to protect against extension removal or profile reset.";});
$("history-import").addEventListener("click",()=>$("history-file").click());
$("history-file").addEventListener("change",async()=>{const file=$("history-file").files[0];if(!file)return;try{const backup=JSON.parse(await file.text());if(!["webdive-backup","weblens-backup"].includes(backup.format)||!backup.report?.recording?.startedAt)throw new Error("Not a WebDive backup");const id=backup.report.recording.startedAt;await send({type:"IMPORT_RECORDING",report:backup.report});let index=0;for(const detail of backup.details||[]){await send({type:"IMPORT_FILE_DETAIL",recordingId:id,detail});index++;$("notice").textContent=`Restoring source details ${index} / ${backup.details.length}`;}await refreshHistory(id);$("notice").textContent="Backup restored locally.";}catch(error){$("notice").textContent=`Could not import backup: ${error.message}`;}finally{$("history-file").value="";}});
refreshHistory().catch(error=>{$("notice").textContent=`Could not load run history: ${error.message}`;});
